[package]
name = "galaxy_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = { workspace = true }
bevy = { workspace = true }
bevy_mod_picking = { workspace = true }
galaxy = { workspace = true }
galaxy_math = { workspace = true }
log = { workspace = true }
