[package]
name = "galaxy-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
bevy = "0.13.2"
bevy_math = "0.13.2"
bevy_prng = { version = "0.6.0", features = ["rand_chacha"] }
bevy_rand = "0.6.0"
rand = "0.8.5"
rand_core = "0.6.4"
rand_distr = "0.4.3"

[profile.release]
opt-level = 3
# lto = true
